image: gitpod/workspace-postgres

tasks:
  - init: pnpm install
    command: |
      export HMR_HOST=`gp url 3000` 
      echo "Starting development server..."
      pnpm run dev

ports:
  - port: 3000
    onOpen: open-browser
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - svelte.svelte-vscode

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true